### ISSUE TITLE
Converting image RGB to BGR

### ISSUE THREAD

**Issue by Auth0rM0rgan** [dgurkaynak/marvel-finetuning#6]
Hey @dgurkaynak,

In AlexNet model, images should convert from RGB to BGR as it's mentioned in the AlexNet paper. I couldn't find where did you convert images. Can you tell me which line in your code?

thanks

**Comment by dgurkaynak** [comment]
Actually I didn't know that. I just quickly scanned AlexNet paper, but couldn't see. Can you refer it? As far as I know, it shouldn't be related with the model itself, because RGB are just independent dimensions. The order of them shouldn't matter as long as they are consistent, **IF** you are training from scratch. 

But we're using pre-trained weights here. So I have checked their training fashion, there is no specific information. But all of them are converted from Caffe. According to [their wiki page](https://github.com/BVLC/caffe/wiki/Image-Format:-BGR-not-RGB), they must be BGR. 

We're using opencv for reading images and it also uses BGR. So, we are fine :)

Nice point, thanks :+1:
