### ISSUE TITLE
About AlexNet

### ISSUE THREAD

**Issue by MuZiGuYue** [dgurkaynak/marvel-finetuning#8]
Hello. In AlexNet, what I understand about your code is that you only train the fc8 and fc7 layers, and the weights of other layers remain unchanged. Is that true? Do the weights of the fc8 and fc7 layers need to be initialized? The following form:
`weights = tf.get_variable('weights', shape=[num_in, num_out],
                                      initializer=tf.truncated_normal_initializer(stddev=0.005),
                                      trainable=True)`
`biases = tf.get_variable('biases', [num_out],
                                     initializer=tf.constant_initializer(1.0), trainable=True)`

**Comment by dgurkaynak** [comment]
In tensorflow, every variable needs to be initialized. After initialization, weights of all the layers except last layer (fc8) are copied from pre-trained model. Because most probably you're not classifying 1000 different classes. During training, just the layers specified with `--train_layers` flag (by default it's `fc7,fc8`) are being trained. All the other layers are frozen. That's why it's called fine-tuning.
